---
name: Astro-SIMBAD-Client
version: 0.002
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Fetch astronomical data from SIMBAD 4.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  LWP::UserAgent: 0
  SOAP::Lite: 0
dynamic_config: 1
provides:
  Astro::SIMBAD::Client:
    file: lib/Astro/SIMBAD/Client.pm
    version: 0.002
  Astro::SIMBAD::Client::WSQueryInterfaceService:
    file: lib/Astro/SIMBAD/Client.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
